services:
  db:
    image: mariadb:11.5
    ports:
      - ${DB_PORT}:3306
    volumes:
      - homethings_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  homethings_data: