package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i git.dmitriygnatenko.ru/dima/homethings/internal/interfaces.IPlaceThingRepository -o ./mocks/i_place_thing_repository_minimock.go -n IPlaceThingRepositoryMock

import (
	"context"
	"database/sql"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"git.dmitriygnatenko.ru/dima/homethings/internal/models"
	"github.com/gojuno/minimock/v3"
)

// IPlaceThingRepositoryMock implements interfaces.IPlaceThingRepository
type IPlaceThingRepositoryMock struct {
	t minimock.Tester

	funcAdd          func(ctx context.Context, req models.AddPlaceThingRequest, tx *sql.Tx) (err error)
	inspectFuncAdd   func(ctx context.Context, req models.AddPlaceThingRequest, tx *sql.Tx)
	afterAddCounter  uint64
	beforeAddCounter uint64
	AddMock          mIPlaceThingRepositoryMockAdd
}

// NewIPlaceThingRepositoryMock returns a mock for interfaces.IPlaceThingRepository
func NewIPlaceThingRepositoryMock(t minimock.Tester) *IPlaceThingRepositoryMock {
	m := &IPlaceThingRepositoryMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddMock = mIPlaceThingRepositoryMockAdd{mock: m}
	m.AddMock.callArgs = []*IPlaceThingRepositoryMockAddParams{}

	return m
}

type mIPlaceThingRepositoryMockAdd struct {
	mock               *IPlaceThingRepositoryMock
	defaultExpectation *IPlaceThingRepositoryMockAddExpectation
	expectations       []*IPlaceThingRepositoryMockAddExpectation

	callArgs []*IPlaceThingRepositoryMockAddParams
	mutex    sync.RWMutex
}

// IPlaceThingRepositoryMockAddExpectation specifies expectation struct of the IPlaceThingRepository.Add
type IPlaceThingRepositoryMockAddExpectation struct {
	mock    *IPlaceThingRepositoryMock
	params  *IPlaceThingRepositoryMockAddParams
	results *IPlaceThingRepositoryMockAddResults
	Counter uint64
}

// IPlaceThingRepositoryMockAddParams contains parameters of the IPlaceThingRepository.Add
type IPlaceThingRepositoryMockAddParams struct {
	ctx context.Context
	req models.AddPlaceThingRequest
	tx  *sql.Tx
}

// IPlaceThingRepositoryMockAddResults contains results of the IPlaceThingRepository.Add
type IPlaceThingRepositoryMockAddResults struct {
	err error
}

// Expect sets up expected params for IPlaceThingRepository.Add
func (mmAdd *mIPlaceThingRepositoryMockAdd) Expect(ctx context.Context, req models.AddPlaceThingRequest, tx *sql.Tx) *mIPlaceThingRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("IPlaceThingRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &IPlaceThingRepositoryMockAddExpectation{}
	}

	mmAdd.defaultExpectation.params = &IPlaceThingRepositoryMockAddParams{ctx, req, tx}
	for _, e := range mmAdd.expectations {
		if minimock.Equal(e.params, mmAdd.defaultExpectation.params) {
			mmAdd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAdd.defaultExpectation.params)
		}
	}

	return mmAdd
}

// Inspect accepts an inspector function that has same arguments as the IPlaceThingRepository.Add
func (mmAdd *mIPlaceThingRepositoryMockAdd) Inspect(f func(ctx context.Context, req models.AddPlaceThingRequest, tx *sql.Tx)) *mIPlaceThingRepositoryMockAdd {
	if mmAdd.mock.inspectFuncAdd != nil {
		mmAdd.mock.t.Fatalf("Inspect function is already set for IPlaceThingRepositoryMock.Add")
	}

	mmAdd.mock.inspectFuncAdd = f

	return mmAdd
}

// Return sets up results that will be returned by IPlaceThingRepository.Add
func (mmAdd *mIPlaceThingRepositoryMockAdd) Return(err error) *IPlaceThingRepositoryMock {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("IPlaceThingRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &IPlaceThingRepositoryMockAddExpectation{mock: mmAdd.mock}
	}
	mmAdd.defaultExpectation.results = &IPlaceThingRepositoryMockAddResults{err}
	return mmAdd.mock
}

// Set uses given function f to mock the IPlaceThingRepository.Add method
func (mmAdd *mIPlaceThingRepositoryMockAdd) Set(f func(ctx context.Context, req models.AddPlaceThingRequest, tx *sql.Tx) (err error)) *IPlaceThingRepositoryMock {
	if mmAdd.defaultExpectation != nil {
		mmAdd.mock.t.Fatalf("Default expectation is already set for the IPlaceThingRepository.Add method")
	}

	if len(mmAdd.expectations) > 0 {
		mmAdd.mock.t.Fatalf("Some expectations are already set for the IPlaceThingRepository.Add method")
	}

	mmAdd.mock.funcAdd = f
	return mmAdd.mock
}

// When sets expectation for the IPlaceThingRepository.Add which will trigger the result defined by the following
// Then helper
func (mmAdd *mIPlaceThingRepositoryMockAdd) When(ctx context.Context, req models.AddPlaceThingRequest, tx *sql.Tx) *IPlaceThingRepositoryMockAddExpectation {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("IPlaceThingRepositoryMock.Add mock is already set by Set")
	}

	expectation := &IPlaceThingRepositoryMockAddExpectation{
		mock:   mmAdd.mock,
		params: &IPlaceThingRepositoryMockAddParams{ctx, req, tx},
	}
	mmAdd.expectations = append(mmAdd.expectations, expectation)
	return expectation
}

// Then sets up IPlaceThingRepository.Add return parameters for the expectation previously defined by the When method
func (e *IPlaceThingRepositoryMockAddExpectation) Then(err error) *IPlaceThingRepositoryMock {
	e.results = &IPlaceThingRepositoryMockAddResults{err}
	return e.mock
}

// Add implements interfaces.IPlaceThingRepository
func (mmAdd *IPlaceThingRepositoryMock) Add(ctx context.Context, req models.AddPlaceThingRequest, tx *sql.Tx) (err error) {
	mm_atomic.AddUint64(&mmAdd.beforeAddCounter, 1)
	defer mm_atomic.AddUint64(&mmAdd.afterAddCounter, 1)

	if mmAdd.inspectFuncAdd != nil {
		mmAdd.inspectFuncAdd(ctx, req, tx)
	}

	mm_params := &IPlaceThingRepositoryMockAddParams{ctx, req, tx}

	// Record call args
	mmAdd.AddMock.mutex.Lock()
	mmAdd.AddMock.callArgs = append(mmAdd.AddMock.callArgs, mm_params)
	mmAdd.AddMock.mutex.Unlock()

	for _, e := range mmAdd.AddMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAdd.AddMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAdd.AddMock.defaultExpectation.Counter, 1)
		mm_want := mmAdd.AddMock.defaultExpectation.params
		mm_got := IPlaceThingRepositoryMockAddParams{ctx, req, tx}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAdd.t.Errorf("IPlaceThingRepositoryMock.Add got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAdd.AddMock.defaultExpectation.results
		if mm_results == nil {
			mmAdd.t.Fatal("No results are set for the IPlaceThingRepositoryMock.Add")
		}
		return (*mm_results).err
	}
	if mmAdd.funcAdd != nil {
		return mmAdd.funcAdd(ctx, req, tx)
	}
	mmAdd.t.Fatalf("Unexpected call to IPlaceThingRepositoryMock.Add. %v %v %v", ctx, req, tx)
	return
}

// AddAfterCounter returns a count of finished IPlaceThingRepositoryMock.Add invocations
func (mmAdd *IPlaceThingRepositoryMock) AddAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.afterAddCounter)
}

// AddBeforeCounter returns a count of IPlaceThingRepositoryMock.Add invocations
func (mmAdd *IPlaceThingRepositoryMock) AddBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.beforeAddCounter)
}

// Calls returns a list of arguments used in each call to IPlaceThingRepositoryMock.Add.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAdd *mIPlaceThingRepositoryMockAdd) Calls() []*IPlaceThingRepositoryMockAddParams {
	mmAdd.mutex.RLock()

	argCopy := make([]*IPlaceThingRepositoryMockAddParams, len(mmAdd.callArgs))
	copy(argCopy, mmAdd.callArgs)

	mmAdd.mutex.RUnlock()

	return argCopy
}

// MinimockAddDone returns true if the count of the Add invocations corresponds
// the number of defined expectations
func (m *IPlaceThingRepositoryMock) MinimockAddDone() bool {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		return false
	}
	return true
}

// MinimockAddInspect logs each unmet expectation
func (m *IPlaceThingRepositoryMock) MinimockAddInspect() {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IPlaceThingRepositoryMock.Add with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		if m.AddMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to IPlaceThingRepositoryMock.Add")
		} else {
			m.t.Errorf("Expected call to IPlaceThingRepositoryMock.Add with params: %#v", *m.AddMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		m.t.Error("Expected call to IPlaceThingRepositoryMock.Add")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IPlaceThingRepositoryMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockAddInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IPlaceThingRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IPlaceThingRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddDone()
}
